Repository team0102/weather-frontend, pull requests merged in 2024-01, with the labels that each got.

#1 [WEA-2]:lipstick:공통 체크박스컴포넌트 개발완료
  public/images/TestImg/Test.png
  src/components/Checkbox/Checkbox.jsx
  src/components/Checkbox/Checkbox.scss
  src/pages/Main/Main.jsx
  src/styles/partials/mixin.scss
Labels: 병합요청, 완료

#4 :lipstick:Components/radio
  src/components/Checkbox/Checkbox.jsx
  src/components/Checkbox/Checkbox.scss
  src/components/Radio/Radio.jsx
  src/components/Radio/Radio.scss
  src/components/RadioGroup/RadioGroup.jsx
  src/components/RadioGroup/RadioGroup.scss
  src/components/TestComponents/Test.jsx
  src/components/TestComponents/Test.scss
  src/data/RadioGenderData.jsx/RadioGenderData.jsx
  src/data/TestData.jsx
  src/pages/Main/Main.jsx
Labels: 완료

#5 스타일링 긴급수정
  src/components/Radio/Radio.scss
  src/styles/partials/variables.scss
Labels: 버그수정료

#2 [WEA-3] :lipstick: Portal 완료
  index.html
  src/pages/Main/Components/Modal/Portal.jsx
Labels: 완료

#6 [WEA-2]:lipstick: 스크롤탑 컴포넌트 완료
  src/Router.jsx
  src/components/ScrollTop/ScrollTop.jsx
Labels: 완료

#10 [WEA-10] :lipstick: Components/modal 완료
  src/components/Modal/CustomModal.jsx
  src/components/Modal/ModalComponents/ModalBox.jsx
  src/components/Modal/ModalComponents/ModalBox.scss
  src/components/Modal/ModalContent/TestModalContent.jsx
  src/components/Modal/TestModal.jsx
  src/components/Nav/Nav.jsx
  src/pages/Main/Main.jsx
Labels: 리뷰반영, 병합요청, 완료

#3 [WEA-8] 💄 Button 완료
  src/components/Button/Button.jsx
  src/components/Button/Button.scss
  src/pages/Main/Main.jsx
Labels: 병합요청, 완료, 리뷰요청

#11 [WEA-9] 💄IconButton 공통 컴포넌트
  src/components/IconButton/IconButton.jsx
  src/components/IconButton/IconButton.scss
  src/pages/Main/Main.jsx
  src/svg/Global/ArrowLeft.svg
  src/svg/Global/ArrowRight.svg
  src/svg/Global/Bookmark.svg
  src/svg/Global/Chat.svg
  src/svg/Global/ChatRound.svg
  src/svg/Global/Comment.svg
  src/svg/Global/CommentRound.svg
  src/svg/Global/Delete.svg
  src/svg/Global/Edit.svg
  src/svg/Global/Feed.svg
  src/svg/Global/Feed9.svg
  src/svg/Global/Hamburger.svg
  src/svg/Global/Home.svg
  src/svg/Global/Image.svg
  src/svg/Global/Like.svg
  src/svg/Global/Location.svg
  src/svg/Global/Notification.svg
  src/svg/Global/Search.svg
  src/svg/Global/Test.svg.example
  src/svg/Global/User.svg
  src/svg/Global/X.svg
Labels: 병합요청, 완료, 리뷰요청

#14 [WEA-19] :lipstick: 글로벌 스크롤 탑이동 버튼
  src/Router.jsx
  src/components/GlobalTopButton/GlobalTopButton.jsx
  src/components/GlobalTopButton/GlobalTopButton.scss
  src/svg/Global/Test.svg.example
  src/svg/Global/topArrow.svg
Labels: 리뷰반영, 병합요청, 완료

#12 [WEA-11] 💄 공통컴포넌트 셀렉트박스
  src/components/SelectBox/Selectbox.jsx
  src/components/SelectBox/Selectbox.scss
  src/pages/Main/Main.jsx
Labels: 병합요청, 완료

#15 [WEA-12] :lipstick: Component/footer
  package-lock.json
  package.json
  src/Router.jsx
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.scss
  src/components/IconButton/IconButton.scss
  src/data/FooterData/FooterIconData.jsx
  src/data/FooterData/FooterItemData.jsx
  src/styles/partials/variables.scss
Labels: 리뷰요청

#13 [WEA-18] 💄 textarea 완료
  src/components/TextArea/TextArea.jsx
  src/components/TextArea/TextArea.scss
  src/pages/Main/Main.jsx
Labels: 리뷰요청

#18 [WEA-16] :art: 글로벌 스타일 수정
  src/styles/base/common.scss
Labels: 완료

#17 [WEA-14] :art: 간격 수정
  src/components/Chip/ChipGroup.scss
  src/components/Chip/Component/Chip.scss
  src/pages/Main/Main.jsx
Labels: 병합요청

#16 [WEA-13] 💄 Component/header
  config.js
  public/data/PopularSearchesData.json
  public/data/SearchPageData.json
  src/Router.jsx
  src/components/Header/Components/DeviceHeader.jsx
  src/components/Header/Components/WebHeader.jsx
  src/components/Header/Header.jsx
  src/components/Header/Header.scss
  src/pages/Main/Main.jsx
  src/pages/Search/Components/PopularKeyword.jsx
  src/pages/Search/Components/PopularKeyword.scss
  src/pages/Search/Search.jsx
  src/pages/Search/Search.scss
  src/pages/Test.jsx
Labels: 리뷰요청

#22 [WEA-25] :lipstick: ui/mypage
  public/data/Test.json
  public/images/TestImg/profile.png
  public/images/TestImg/참고.js
  src/Router.jsx
  src/components/GlobalTopButton/GlobalTopButton.scss
  src/components/Header/Components/WebHeader.jsx
  src/components/Header/Header.jsx
  src/components/Input/Input.jsx
  src/components/Input/Input.scss
  src/components/Nav/Nav.scss
  src/pages/Main/Main.jsx
  src/pages/MyInfo/MyInfo.jsx
  src/pages/MyInfo/MyInfo.scss
  src/pages/Test.jsx
  src/styles/base/common.scss
  src/styles/partials/mixin.scss
  src/svg/Global/Check.svg
  src/svg/Global/Follower.svg
Labels: 병합요청
